name: textifier ci

on:
  push:
    branches:
      master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      WEB_PATH: $web
      ACCOUNT: ${{ secrets.account }}
      KEY: ${{ secrets.key }}
    steps:
    # checkout the repo
    - uses: actions/checkout@master
    
    # install 11ty, build site
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present

    # clear old site
    - name: clear old site
      run : |
        az storage blob delete-batch --source $WEB_PATH --account-name $ACCOUNT --account-key $KEY

    # push to azure storage
    - name: push to azure storage
      run : |
        az storage blob upload-batch -s dist -d $WEB_PATH --account-name $ACCOUNT --account-key $KEY