name: textifier ci

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master
    
    # install dependencies, build, and test
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
    # zip/package
    - name: package contents
      run: |
        cd dist
        zip -r build.zip *
        cd ..
        mv dist/build.zip .
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.CREDENTIALS }}

    - run: |
        az webapp deployment source config-zip -g ${{ secrets.RG }} -n ${{ secrets.APP }} --src build.zip